pk=[(b'Bulbasaur', ('Grass', 'Poison')),
 (b'Ivysaur', ('Grass', 'Poison')),
 (b'Venusaur', ('Grass', 'Poison')),
 (b'Charmander', ('Fire',)),
 (b'Charmeleon', ('Fire',)),
 (b'Charizard', ('Fire', 'Flying')),
 (b'Squirtle', ('Water',)),
 (b'Wartortle', ('Water',)),
 (b'Blastoise', ('Water',)),
 (b'Caterpie', ('Bug',)),
 (b'Metapod', ('Bug',)),
 (b'Butterfree', ('Bug', 'Flying')),
 (b'Weedle', ('Bug', 'Poison')),
 (b'Kakuna', ('Bug', 'Poison')),
 (b'Beedrill', ('Bug', 'Poison')),
 (b'Pidgey', ('Normal', 'Flying')),
 (b'Pidgeotto', ('Normal', 'Flying')),
 (b'Pidgeot', ('Normal', 'Flying')),
 (b'Rattata', ('Normal',)),
 (b'Raticate', ('Normal',)),
 (b'Spearow', ('Normal', 'Flying')),
 (b'Fearow', ('Normal', 'Flying')),
 (b'Ekans', ('Poison',)),
 (b'Arbok', ('Poison',)),
 (b'Pikachu', ('Electric',)),
 (b'Raichu', ('Electric',)),
 (b'Sandshrew', ('Ground',)),
 (b'Sandslash', ('Ground',)),
 (b'Nidoran\xe2\x99\x80', ('Poison',)),
 (b'Nidorina', ('Poison',)),
 (b'Nidoqueen', ('Poison', 'Ground')),
 (b'Nidoran\xe2\x99\x82', ('Poison',)),
 (b'Nidorino', ('Poison',)),
 (b'Nidoking', ('Poison', 'Ground')),
 (b'Clefairy', ('Fairy',)),
 (b'Clefable', ('Fairy',)),
 (b'Vulpix', ('Fire',)),
 (b'Ninetales', ('Fire',)),
 (b'Jigglypuff', ('Normal', 'Fairy')),
 (b'Wigglytuff', ('Normal', 'Fairy')),
 (b'Zubat', ('Poison', 'Flying')),
 (b'Golbat', ('Poison', 'Flying')),
 (b'Oddish', ('Grass', 'Poison')),
 (b'Gloom', ('Grass', 'Poison')),
 (b'Vileplume', ('Grass', 'Poison')),
 (b'Paras', ('Bug', 'Grass')),
 (b'Parasect', ('Bug', 'Grass')),
 (b'Venonat', ('Bug', 'Poison')),
 (b'Venomoth', ('Bug', 'Poison')),
 (b'Diglett', ('Ground',)),
 (b'Dugtrio', ('Ground',)),
 (b'Meowth', ('Normal',)),
 (b'Persian', ('Normal',)),
 (b'Psyduck', ('Water',)),
 (b'Golduck', ('Water',)),
 (b'Mankey', ('Fighting',)),
 (b'Primeape', ('Fighting',)),
 (b'Growlithe', ('Fire',)),
 (b'Arcanine', ('Fire',)),
 (b'Poliwag', ('Water',)),
 (b'Poliwhirl', ('Water',)),
 (b'Poliwrath', ('Water', 'Fighting')),
 (b'Abra', ('Psychic',)),
 (b'Kadabra', ('Psychic',)),
 (b'Alakazam', ('Psychic',)),
 (b'Machop', ('Fighting',)),
 (b'Machoke', ('Fighting',)),
 (b'Machamp', ('Fighting',)),
 (b'Bellsprout', ('Grass', 'Poison')),
 (b'Weepinbell', ('Grass', 'Poison')),
 (b'Victreebel', ('Grass', 'Poison')),
 (b'Tentacool', ('Water', 'Poison')),
 (b'Tentacruel', ('Water', 'Poison')),
 (b'Geodude', ('Rock', 'Ground')),
 (b'Graveler', ('Rock', 'Ground')),
 (b'Golem', ('Rock', 'Ground')),
 (b'Ponyta', ('Fire',)),
 (b'Rapidash', ('Fire',)),
 (b'Slowpoke', ('Water', 'Psychic')),
 (b'Slowbro', ('Water', 'Psychic')),
 (b'Magnemite', ('Electric', 'Steel')),
 (b'Magneton', ('Electric', 'Steel')),
 (b"Farfetch'd", ('Normal', 'Flying')),
 (b'Doduo', ('Normal', 'Flying')),
 (b'Dodrio', ('Normal', 'Flying')),
 (b'Seel', ('Water',)),
 (b'Dewgong', ('Water', 'Ice')),
 (b'Grimer', ('Poison',)),
 (b'Muk', ('Poison',)),
 (b'Shellder', ('Water',)),
 (b'Cloyster', ('Water', 'Ice')),
 (b'Gastly', ('Ghost', 'Poison')),
 (b'Haunter', ('Ghost', 'Poison')),
 (b'Gengar', ('Ghost', 'Poison')),
 (b'Onix', ('Rock', 'Ground')),
 (b'Drowzee', ('Psychic',)),
 (b'Hypno', ('Psychic',)),
 (b'Krabby', ('Water',)),
 (b'Kingler', ('Water',)),
 (b'Voltorb', ('Electric',)),
 (b'Electrode', ('Electric',)),
 (b'Exeggcute', ('Grass', 'Psychic')),
 (b'Exeggutor', ('Grass', 'Psychic')),
 (b'Cubone', ('Ground',)),
 (b'Marowak', ('Ground',)),
 (b'Hitmonlee', ('Fighting',)),
 (b'Hitmonchan', ('Fighting',)),
 (b'Lickitung', ('Normal',)),
 (b'Koffing', ('Poison',)),
 (b'Weezing', ('Poison',)),
 (b'Rhyhorn', ('Ground', 'Rock')),
 (b'Rhydon', ('Ground', 'Rock')),
 (b'Chansey', ('Normal',)),
 (b'Tangela', ('Grass',)),
 (b'Kangaskhan', ('Normal',)),
 (b'Horsea', ('Water',)),
 (b'Seadra', ('Water',)),
 (b'Goldeen', ('Water',)),
 (b'Seaking', ('Water',)),
 (b'Staryu', ('Water',)),
 (b'Starmie', ('Water', 'Psychic')),
 (b'Mr. Mime', ('Psychic', 'Fairy')),
 (b'Scyther', ('Bug', 'Flying')),
 (b'Jynx', ('Ice', 'Psychic')),
 (b'Electabuzz', ('Electric',)),
 (b'Magmar', ('Fire',)),
 (b'Pinsir', ('Bug',)),
 (b'Tauros', ('Normal',)),
 (b'Magikarp', ('Water',)),
 (b'Gyarados', ('Water', 'Flying')),
 (b'Lapras', ('Water', 'Ice')),
 (b'Ditto', ('Normal',)),
 (b'Eevee', ('Normal',)),
 (b'Vaporeon', ('Water',)),
 (b'Jolteon', ('Electric',)),
 (b'Flareon', ('Fire',)),
 (b'Porygon', ('Normal',)),
 (b'Omanyte', ('Rock', 'Water')),
 (b'Omastar', ('Rock', 'Water')),
 (b'Kabuto', ('Rock', 'Water')),
 (b'Kabutops', ('Rock', 'Water')),
 (b'Aerodactyl', ('Rock', 'Flying')),
 (b'Snorlax', ('Normal',)),
 (b'Articuno', ('Ice', 'Flying')),
 (b'Zapdos', ('Electric', 'Flying')),
 (b'Moltres', ('Fire', 'Flying')),
 (b'Dratini', ('Dragon',)),
 (b'Dragonair', ('Dragon',)),
 (b'Dragonite', ('Dragon', 'Flying')),
 (b'Mewtwo', ('Psychic',)),
 (b'Mew', ('Psychic',)),
 (b'Chikorita', ('Grass',)),
 (b'Bayleef', ('Grass',)),
 (b'Meganium', ('Grass',)),
 (b'Cyndaquil', ('Fire',)),
 (b'Quilava', ('Fire',)),
 (b'Typhlosion', ('Fire',)),
 (b'Totodile', ('Water',)),
 (b'Croconaw', ('Water',)),
 (b'Feraligatr', ('Water',)),
 (b'Sentret', ('Normal',)),
 (b'Furret', ('Normal',)),
 (b'Hoothoot', ('Normal', 'Flying')),
 (b'Noctowl', ('Normal', 'Flying')),
 (b'Ledyba', ('Bug', 'Flying')),
 (b'Ledian', ('Bug', 'Flying')),
 (b'Spinarak', ('Bug', 'Poison')),
 (b'Ariados', ('Bug', 'Poison')),
 (b'Crobat', ('Poison', 'Flying')),
 (b'Chinchou', ('Water', 'Electric')),
 (b'Lanturn', ('Water', 'Electric')),
 (b'Pichu', ('Electric',)),
 (b'Cleffa', ('Fairy',)),
 (b'Igglybuff', ('Normal', 'Fairy')),
 (b'Togepi', ('Fairy',)),
 (b'Togetic', ('Fairy', 'Flying')),
 (b'Natu', ('Psychic', 'Flying')),
 (b'Xatu', ('Psychic', 'Flying')),
 (b'Mareep', ('Electric',)),
 (b'Flaaffy', ('Electric',)),
 (b'Ampharos', ('Electric',)),
 (b'Bellossom', ('Grass',)),
 (b'Marill', ('Water', 'Fairy')),
 (b'Azumarill', ('Water', 'Fairy')),
 (b'Sudowoodo', ('Rock',)),
 (b'Politoed', ('Water',)),
 (b'Hoppip', ('Grass', 'Flying')),
 (b'Skiploom', ('Grass', 'Flying')),
 (b'Jumpluff', ('Grass', 'Flying')),
 (b'Aipom', ('Normal',)),
 (b'Sunkern', ('Grass',)),
 (b'Sunflora', ('Grass',)),
 (b'Yanma', ('Bug', 'Flying')),
 (b'Wooper', ('Water', 'Ground')),
 (b'Quagsire', ('Water', 'Ground')),
 (b'Espeon', ('Psychic',)),
 (b'Umbreon', ('Dark',)),
 (b'Murkrow', ('Dark', 'Flying')),
 (b'Slowking', ('Water', 'Psychic')),
 (b'Misdreavus', ('Ghost',)),
 (b'Unown', ('Psychic',)),
 (b'Wobbuffet', ('Psychic',)),
 (b'Girafarig', ('Normal', 'Psychic')),
 (b'Pineco', ('Bug',)),
 (b'Forretress', ('Bug', 'Steel')),
 (b'Dunsparce', ('Normal',)),
 (b'Gligar', ('Ground', 'Flying')),
 (b'Steelix', ('Steel', 'Ground')),
 (b'Snubbull', ('Fairy',)),
 (b'Granbull', ('Fairy',)),
 (b'Qwilfish', ('Water', 'Poison')),
 (b'Scizor', ('Bug', 'Steel')),
 (b'Shuckle', ('Bug', 'Rock')),
 (b'Heracross', ('Bug', 'Fighting')),
 (b'Sneasel', ('Dark', 'Ice')),
 (b'Teddiursa', ('Normal',)),
 (b'Ursaring', ('Normal',)),
 (b'Slugma', ('Fire',)),
 (b'Magcargo', ('Fire', 'Rock')),
 (b'Swinub', ('Ice', 'Ground')),
 (b'Piloswine', ('Ice', 'Ground')),
 (b'Corsola', ('Water', 'Rock')),
 (b'Remoraid', ('Water',)),
 (b'Octillery', ('Water',)),
 (b'Delibird', ('Ice', 'Flying')),
 (b'Mantine', ('Water', 'Flying')),
 (b'Skarmory', ('Steel', 'Flying')),
 (b'Houndour', ('Dark', 'Fire')),
 (b'Houndoom', ('Dark', 'Fire')),
 (b'Kingdra', ('Water', 'Dragon')),
 (b'Phanpy', ('Ground',)),
 (b'Donphan', ('Ground',)),
 (b'Porygon2', ('Normal',)),
 (b'Stantler', ('Normal',)),
 (b'Smeargle', ('Normal',)),
 (b'Tyrogue', ('Fighting',)),
 (b'Hitmontop', ('Fighting',)),
 (b'Smoochum', ('Ice', 'Psychic')),
 (b'Elekid', ('Electric',)),
 (b'Magby', ('Fire',)),
 (b'Miltank', ('Normal',)),
 (b'Blissey', ('Normal',)),
 (b'Raikou', ('Electric',)),
 (b'Entei', ('Fire',)),
 (b'Suicune', ('Water',)),
 (b'Larvitar', ('Rock', 'Ground')),
 (b'Pupitar', ('Rock', 'Ground')),
 (b'Tyranitar', ('Rock', 'Dark')),
 (b'Lugia', ('Psychic', 'Flying')),
 (b'Ho-oh', ('Fire', 'Flying')),
 (b'Celebi', ('Psychic', 'Grass')),
 (b'Treecko', ('Grass',)),
 (b'Grovyle', ('Grass',)),
 (b'Sceptile', ('Grass',)),
 (b'Torchic', ('Fire',)),
 (b'Combusken', ('Fire', 'Fighting')),
 (b'Blaziken', ('Fire', 'Fighting')),
 (b'Mudkip', ('Water',)),
 (b'Marshtomp', ('Water', 'Ground')),
 (b'Swampert', ('Water', 'Ground')),
 (b'Poochyena', ('Dark',)),
 (b'Mightyena', ('Dark',)),
 (b'Zigzagoon', ('Normal',)),
 (b'Linoone', ('Normal',)),
 (b'Wurmple', ('Bug',)),
 (b'Silcoon', ('Bug',)),
 (b'Beautifly', ('Bug', 'Flying')),
 (b'Cascoon', ('Bug',)),
 (b'Dustox', ('Bug', 'Poison')),
 (b'Lotad', ('Water', 'Grass')),
 (b'Lombre', ('Water', 'Grass')),
 (b'Ludicolo', ('Water', 'Grass')),
 (b'Seedot', ('Grass',)),
 (b'Nuzleaf', ('Grass', 'Dark')),
 (b'Shiftry', ('Grass', 'Dark')),
 (b'Taillow', ('Normal', 'Flying')),
 (b'Swellow', ('Normal', 'Flying')),
 (b'Wingull', ('Water', 'Flying')),
 (b'Pelipper', ('Water', 'Flying')),
 (b'Ralts', ('Psychic', 'Fairy')),
 (b'Kirlia', ('Psychic', 'Fairy')),
 (b'Gardevoir', ('Psychic', 'Fairy')),
 (b'Surskit', ('Bug', 'Water')),
 (b'Masquerain', ('Bug', 'Flying')),
 (b'Shroomish', ('Grass',)),
 (b'Breloom', ('Grass', 'Fighting')),
 (b'Slakoth', ('Normal',)),
 (b'Vigoroth', ('Normal',)),
 (b'Slaking', ('Normal',)),
 (b'Nincada', ('Bug', 'Ground')),
 (b'Ninjask', ('Bug', 'Flying')),
 (b'Shedinja', ('Bug', 'Ghost')),
 (b'Whismur', ('Normal',)),
 (b'Loudred', ('Normal',)),
 (b'Exploud', ('Normal',)),
 (b'Makuhita', ('Fighting',)),
 (b'Hariyama', ('Fighting',)),
 (b'Azurill', ('Normal', 'Fairy')),
 (b'Nosepass', ('Rock',)),
 (b'Skitty', ('Normal',)),
 (b'Delcatty', ('Normal',)),
 (b'Sableye', ('Dark', 'Ghost')),
 (b'Mawile', ('Steel', 'Fairy')),
 (b'Aron', ('Steel', 'Rock')),
 (b'Lairon', ('Steel', 'Rock')),
 (b'Aggron', ('Steel', 'Rock')),
 (b'Meditite', ('Fighting', 'Psychic')),
 (b'Medicham', ('Fighting', 'Psychic')),
 (b'Electrike', ('Electric',)),
 (b'Manectric', ('Electric',)),
 (b'Plusle', ('Electric',)),
 (b'Minun', ('Electric',)),
 (b'Volbeat', ('Bug',)),
 (b'Illumise', ('Bug',)),
 (b'Roselia', ('Grass', 'Poison')),
 (b'Gulpin', ('Poison',)),
 (b'Swalot', ('Poison',)),
 (b'Carvanha', ('Water', 'Dark')),
 (b'Sharpedo', ('Water', 'Dark')),
 (b'Wailmer', ('Water',)),
 (b'Wailord', ('Water',)),
 (b'Numel', ('Fire', 'Ground')),
 (b'Camerupt', ('Fire', 'Ground')),
 (b'Torkoal', ('Fire',)),
 (b'Spoink', ('Psychic',)),
 (b'Grumpig', ('Psychic',)),
 (b'Spinda', ('Normal',)),
 (b'Trapinch', ('Ground',)),
 (b'Vibrava', ('Ground', 'Dragon')),
 (b'Flygon', ('Ground', 'Dragon')),
 (b'Cacnea', ('Grass',)),
 (b'Cacturne', ('Grass', 'Dark')),
 (b'Swablu', ('Normal', 'Flying')),
 (b'Altaria', ('Dragon', 'Flying')),
 (b'Zangoose', ('Normal',)),
 (b'Seviper', ('Poison',)),
 (b'Lunatone', ('Rock', 'Psychic')),
 (b'Solrock', ('Rock', 'Psychic')),
 (b'Barboach', ('Water', 'Ground')),
 (b'Whiscash', ('Water', 'Ground')),
 (b'Corphish', ('Water',)),
 (b'Crawdaunt', ('Water', 'Dark')),
 (b'Baltoy', ('Ground', 'Psychic')),
 (b'Claydol', ('Ground', 'Psychic')),
 (b'Lileep', ('Rock', 'Grass')),
 (b'Cradily', ('Rock', 'Grass')),
 (b'Anorith', ('Rock', 'Bug')),
 (b'Armaldo', ('Rock', 'Bug')),
 (b'Feebas', ('Water',)),
 (b'Milotic', ('Water',)),
 (b'Castform', ('Normal',)),
 (b'Kecleon', ('Normal',)),
 (b'Shuppet', ('Ghost',)),
 (b'Banette', ('Ghost',)),
 (b'Duskull', ('Ghost',)),
 (b'Dusclops', ('Ghost',)),
 (b'Tropius', ('Grass', 'Flying')),
 (b'Chimecho', ('Psychic',)),
 (b'Absol', ('Dark',)),
 (b'Wynaut', ('Psychic',)),
 (b'Snorunt', ('Ice',)),
 (b'Glalie', ('Ice',)),
 (b'Spheal', ('Ice', 'Water')),
 (b'Sealeo', ('Ice', 'Water')),
 (b'Walrein', ('Ice', 'Water')),
 (b'Clamperl', ('Water',)),
 (b'Huntail', ('Water',)),
 (b'Gorebyss', ('Water',)),
 (b'Relicanth', ('Water', 'Rock')),
 (b'Luvdisc', ('Water',)),
 (b'Bagon', ('Dragon',)),
 (b'Shelgon', ('Dragon',)),
 (b'Salamence', ('Dragon', 'Flying')),
 (b'Beldum', ('Steel', 'Psychic')),
 (b'Metang', ('Steel', 'Psychic')),
 (b'Metagross', ('Steel', 'Psychic')),
 (b'Regirock', ('Rock',)),
 (b'Regice', ('Ice',)),
 (b'Registeel', ('Steel',)),
 (b'Latias', ('Dragon', 'Psychic')),
 (b'Latios', ('Dragon', 'Psychic')),
 (b'Kyogre', ('Water',)),
 (b'Groudon', ('Ground',)),
 (b'Rayquaza', ('Dragon', 'Flying')),
 (b'Jirachi', ('Steel', 'Psychic')),
 (b'Deoxys', ('Psychic',)),
 (b'Turtwig', ('Grass',)),
 (b'Grotle', ('Grass',)),
 (b'Torterra', ('Grass', 'Ground')),
 (b'Chimchar', ('Fire',)),
 (b'Monferno', ('Fire', 'Fighting')),
 (b'Infernape', ('Fire', 'Fighting')),
 (b'Piplup', ('Water',)),
 (b'Prinplup', ('Water',)),
 (b'Empoleon', ('Water', 'Steel')),
 (b'Starly', ('Normal', 'Flying')),
 (b'Staravia', ('Normal', 'Flying')),
 (b'Staraptor', ('Normal', 'Flying')),
 (b'Bidoof', ('Normal',)),
 (b'Bibarel', ('Normal', 'Water')),
 (b'Kricketot', ('Bug',)),
 (b'Kricketune', ('Bug',)),
 (b'Shinx', ('Electric',)),
 (b'Luxio', ('Electric',)),
 (b'Luxray', ('Electric',)),
 (b'Budew', ('Grass', 'Poison')),
 (b'Roserade', ('Grass', 'Poison')),
 (b'Cranidos', ('Rock',)),
 (b'Rampardos', ('Rock',)),
 (b'Shieldon', ('Rock', 'Steel')),
 (b'Bastiodon', ('Rock', 'Steel')),
 (b'Burmy', ('Bug',)),
 (b'Wormadam', ('Bug', 'Grass')),
 (b'Mothim', ('Bug', 'Flying')),
 (b'Combee', ('Bug', 'Flying')),
 (b'Vespiquen', ('Bug', 'Flying')),
 (b'Pachirisu', ('Electric',)),
 (b'Buizel', ('Water',)),
 (b'Floatzel', ('Water',)),
 (b'Cherubi', ('Grass',)),
 (b'Cherrim', ('Grass',)),
 (b'Shellos', ('Water',)),
 (b'Gastrodon', ('Water', 'Ground')),
 (b'Ambipom', ('Normal',)),
 (b'Drifloon', ('Ghost', 'Flying')),
 (b'Drifblim', ('Ghost', 'Flying')),
 (b'Buneary', ('Normal',)),
 (b'Lopunny', ('Normal',)),
 (b'Mismagius', ('Ghost',)),
 (b'Honchkrow', ('Dark', 'Flying')),
 (b'Glameow', ('Normal',)),
 (b'Purugly', ('Normal',)),
 (b'Chingling', ('Psychic',)),
 (b'Stunky', ('Poison', 'Dark')),
 (b'Skuntank', ('Poison', 'Dark')),
 (b'Bronzor', ('Steel', 'Psychic')),
 (b'Bronzong', ('Steel', 'Psychic')),
 (b'Bonsly', ('Rock',)),
 (b'Mime Jr.', ('Psychic', 'Fairy')),
 (b'Happiny', ('Normal',)),
 (b'Chatot', ('Normal', 'Flying')),
 (b'Spiritomb', ('Ghost', 'Dark')),
 (b'Gible', ('Dragon', 'Ground')),
 (b'Gabite', ('Dragon', 'Ground')),
 (b'Garchomp', ('Dragon', 'Ground')),
 (b'Munchlax', ('Normal',)),
 (b'Riolu', ('Fighting',)),
 (b'Lucario', ('Fighting', 'Steel')),
 (b'Hippopotas', ('Ground',)),
 (b'Hippowdon', ('Ground',)),
 (b'Skorupi', ('Poison', 'Bug')),
 (b'Drapion', ('Poison', 'Dark')),
 (b'Croagunk', ('Poison', 'Fighting')),
 (b'Toxicroak', ('Poison', 'Fighting')),
 (b'Carnivine', ('Grass',)),
 (b'Finneon', ('Water',)),
 (b'Lumineon', ('Water',)),
 (b'Mantyke', ('Water', 'Flying')),
 (b'Snover', ('Grass', 'Ice')),
 (b'Abomasnow', ('Grass', 'Ice')),
 (b'Weavile', ('Dark', 'Ice')),
 (b'Magnezone', ('Electric', 'Steel')),
 (b'Lickilicky', ('Normal',)),
 (b'Rhyperior', ('Ground', 'Rock')),
 (b'Tangrowth', ('Grass',)),
 (b'Electivire', ('Electric',)),
 (b'Magmortar', ('Fire',)),
 (b'Togekiss', ('Fairy', 'Flying')),
 (b'Yanmega', ('Bug', 'Flying')),
 (b'Leafeon', ('Grass',)),
 (b'Glaceon', ('Ice',)),
 (b'Gliscor', ('Ground', 'Flying')),
 (b'Mamoswine', ('Ice', 'Ground')),
 (b'Porygon-Z', ('Normal',)),
 (b'Gallade', ('Psychic', 'Fighting')),
 (b'Probopass', ('Rock', 'Steel')),
 (b'Dusknoir', ('Ghost',)),
 (b'Froslass', ('Ice', 'Ghost')),
 (b'Rotom', ('Electric', 'Ghost')),
 (b'Uxie', ('Psychic',)),
 (b'Mesprit', ('Psychic',)),
 (b'Azelf', ('Psychic',)),
 (b'Dialga', ('Steel', 'Dragon')),
 (b'Palkia', ('Water', 'Dragon')),
 (b'Heatran', ('Fire', 'Steel')),
 (b'Regigigas', ('Normal',)),
 (b'Giratina', ('Ghost', 'Dragon')),
 (b'Cresselia', ('Psychic',)),
 (b'Phione', ('Water',)),
 (b'Manaphy', ('Water',)),
 (b'Darkrai', ('Dark',)),
 (b'Shaymin', ('Grass',)),
 (b'Arceus', ('Normal',)),
 (b'Victini', ('Psychic', 'Fire')),
 (b'Snivy', ('Grass',)),
 (b'Servine', ('Grass',)),
 (b'Serperior', ('Grass',)),
 (b'Tepig', ('Fire',)),
 (b'Pignite', ('Fire', 'Fighting')),
 (b'Emboar', ('Fire', 'Fighting')),
 (b'Oshawott', ('Water',)),
 (b'Dewott', ('Water',)),
 (b'Samurott', ('Water',)),
 (b'Patrat', ('Normal',)),
 (b'Watchog', ('Normal',)),
 (b'Lillipup', ('Normal',)),
 (b'Herdier', ('Normal',)),
 (b'Stoutland', ('Normal',)),
 (b'Purrloin', ('Dark',)),
 (b'Liepard', ('Dark',)),
 (b'Pansage', ('Grass',)),
 (b'Simisage', ('Grass',)),
 (b'Pansear', ('Fire',)),
 (b'Simisear', ('Fire',)),
 (b'Panpour', ('Water',)),
 (b'Simipour', ('Water',)),
 (b'Munna', ('Psychic',)),
 (b'Musharna', ('Psychic',)),
 (b'Pidove', ('Normal', 'Flying')),
 (b'Tranquill', ('Normal', 'Flying')),
 (b'Unfezant', ('Normal', 'Flying')),
 (b'Blitzle', ('Electric',)),
 (b'Zebstrika', ('Electric',)),
 (b'Roggenrola', ('Rock',)),
 (b'Boldore', ('Rock',)),
 (b'Gigalith', ('Rock',)),
 (b'Woobat', ('Psychic', 'Flying')),
 (b'Swoobat', ('Psychic', 'Flying')),
 (b'Drilbur', ('Ground',)),
 (b'Excadrill', ('Ground', 'Steel')),
 (b'Audino', ('Normal',)),
 (b'Timburr', ('Fighting',)),
 (b'Gurdurr', ('Fighting',)),
 (b'Conkeldurr', ('Fighting',)),
 (b'Tympole', ('Water',)),
 (b'Palpitoad', ('Water', 'Ground')),
 (b'Seismitoad', ('Water', 'Ground')),
 (b'Throh', ('Fighting',)),
 (b'Sawk', ('Fighting',)),
 (b'Sewaddle', ('Bug', 'Grass')),
 (b'Swadloon', ('Bug', 'Grass')),
 (b'Leavanny', ('Bug', 'Grass')),
 (b'Venipede', ('Bug', 'Poison')),
 (b'Whirlipede', ('Bug', 'Poison')),
 (b'Scolipede', ('Bug', 'Poison')),
 (b'Cottonee', ('Grass', 'Fairy')),
 (b'Whimsicott', ('Grass', 'Fairy')),
 (b'Petilil', ('Grass',)),
 (b'Lilligant', ('Grass',)),
 (b'Basculin', ('Water',)),
 (b'Sandile', ('Ground', 'Dark')),
 (b'Krokorok', ('Ground', 'Dark')),
 (b'Krookodile', ('Ground', 'Dark')),
 (b'Darumaka', ('Fire',)),
 (b'Darmanitan', ('Fire',)),
 (b'Maractus', ('Grass',)),
 (b'Dwebble', ('Bug', 'Rock')),
 (b'Crustle', ('Bug', 'Rock')),
 (b'Scraggy', ('Dark', 'Fighting')),
 (b'Scrafty', ('Dark', 'Fighting')),
 (b'Sigilyph', ('Psychic', 'Flying')),
 (b'Yamask', ('Ghost',)),
 (b'Cofagrigus', ('Ghost',)),
 (b'Tirtouga', ('Water', 'Rock')),
 (b'Carracosta', ('Water', 'Rock')),
 (b'Archen', ('Rock', 'Flying')),
 (b'Archeops', ('Rock', 'Flying')),
 (b'Trubbish', ('Poison',)),
 (b'Garbodor', ('Poison',)),
 (b'Zorua', ('Dark',)),
 (b'Zoroark', ('Dark',)),
 (b'Minccino', ('Normal',)),
 (b'Cinccino', ('Normal',)),
 (b'Gothita', ('Psychic',)),
 (b'Gothorita', ('Psychic',)),
 (b'Gothitelle', ('Psychic',)),
 (b'Solosis', ('Psychic',)),
 (b'Duosion', ('Psychic',)),
 (b'Reuniclus', ('Psychic',)),
 (b'Ducklett', ('Water', 'Flying')),
 (b'Swanna', ('Water', 'Flying')),
 (b'Vanillite', ('Ice',)),
 (b'Vanillish', ('Ice',)),
 (b'Vanilluxe', ('Ice',)),
 (b'Deerling', ('Normal', 'Grass')),
 (b'Sawsbuck', ('Normal', 'Grass')),
 (b'Emolga', ('Electric', 'Flying')),
 (b'Karrablast', ('Bug',)),
 (b'Escavalier', ('Bug', 'Steel')),
 (b'Foongus', ('Grass', 'Poison')),
 (b'Amoonguss', ('Grass', 'Poison')),
 (b'Frillish', ('Water', 'Ghost')),
 (b'Jellicent', ('Water', 'Ghost')),
 (b'Alomomola', ('Water',)),
 (b'Joltik', ('Bug', 'Electric')),
 (b'Galvantula', ('Bug', 'Electric')),
 (b'Ferroseed', ('Grass', 'Steel')),
 (b'Ferrothorn', ('Grass', 'Steel')),
 (b'Klink', ('Steel',)),
 (b'Klang', ('Steel',)),
 (b'Klinklang', ('Steel',)),
 (b'Tynamo', ('Electric',)),
 (b'Eelektrik', ('Electric',)),
 (b'Eelektross', ('Electric',)),
 (b'Elgyem', ('Psychic',)),
 (b'Beheeyem', ('Psychic',)),
 (b'Litwick', ('Ghost', 'Fire')),
 (b'Lampent', ('Ghost', 'Fire')),
 (b'Chandelure', ('Ghost', 'Fire')),
 (b'Axew', ('Dragon',)),
 (b'Fraxure', ('Dragon',)),
 (b'Haxorus', ('Dragon',)),
 (b'Cubchoo', ('Ice',)),
 (b'Beartic', ('Ice',)),
 (b'Cryogonal', ('Ice',)),
 (b'Shelmet', ('Bug',)),
 (b'Accelgor', ('Bug',)),
 (b'Stunfisk', ('Electric', 'Ground')),
 (b'Mienfoo', ('Fighting',)),
 (b'Mienshao', ('Fighting',)),
 (b'Druddigon', ('Dragon',)),
 (b'Golett', ('Ground', 'Ghost')),
 (b'Golurk', ('Ground', 'Ghost')),
 (b'Pawniard', ('Dark', 'Steel')),
 (b'Bisharp', ('Dark', 'Steel')),
 (b'Bouffalant', ('Normal',)),
 (b'Rufflet', ('Normal', 'Flying')),
 (b'Braviary', ('Normal', 'Flying')),
 (b'Vullaby', ('Dark', 'Flying')),
 (b'Mandibuzz', ('Dark', 'Flying')),
 (b'Heatmor', ('Fire',)),
 (b'Durant', ('Bug', 'Steel')),
 (b'Deino', ('Dark', 'Dragon')),
 (b'Zweilous', ('Dark', 'Dragon')),
 (b'Hydreigon', ('Dark', 'Dragon')),
 (b'Larvesta', ('Bug', 'Fire')),
 (b'Volcarona', ('Bug', 'Fire')),
 (b'Cobalion', ('Steel', 'Fighting')),
 (b'Terrakion', ('Rock', 'Fighting')),
 (b'Virizion', ('Grass', 'Fighting')),
 (b'Tornadus', ('Flying',)),
 (b'Thundurus', ('Electric', 'Flying')),
 (b'Reshiram', ('Dragon', 'Fire')),
 (b'Zekrom', ('Dragon', 'Electric')),
 (b'Landorus', ('Ground', 'Flying')),
 (b'Kyurem', ('Dragon', 'Ice')),
 (b'Keldeo', ('Water', 'Fighting')),
 (b'Meloetta', ('Normal', 'Psychic')),
 (b'Genesect', ('Bug', 'Steel')),
 (b'Chespin', ('Grass',)),
 (b'Quilladin', ('Grass',)),
 (b'Chesnaught', ('Grass', 'Fighting')),
 (b'Fennekin', ('Fire',)),
 (b'Braixen', ('Fire',)),
 (b'Delphox', ('Fire', 'Psychic')),
 (b'Froakie', ('Water',)),
 (b'Frogadier', ('Water',)),
 (b'Greninja', ('Water', 'Dark')),
 (b'Bunnelby', ('Normal',)),
 (b'Diggersby', ('Normal', 'Ground')),
 (b'Fletchling', ('Normal', 'Flying')),
 (b'Fletchinder', ('Fire', 'Flying')),
 (b'Talonflame', ('Fire', 'Flying')),
 (b'Scatterbug', ('Bug',)),
 (b'Spewpa', ('Bug',)),
 (b'Vivillon', ('Bug', 'Flying')),
 (b'Litleo', ('Fire', 'Normal')),
 (b'Pyroar', ('Fire', 'Normal')),
 (b'Flab\xc3\xa9b\xc3\xa9', ('Fairy',)),
 (b'Floette', ('Fairy',)),
 (b'Florges', ('Fairy',)),
 (b'Skiddo', ('Grass',)),
 (b'Gogoat', ('Grass',)),
 (b'Pancham', ('Fighting',)),
 (b'Pangoro', ('Fighting', 'Dark')),
 (b'Furfrou', ('Normal',)),
 (b'Espurr', ('Psychic',)),
 (b'Meowstic', ('Psychic',)),
 (b'Honedge', ('Steel', 'Ghost')),
 (b'Doublade', ('Steel', 'Ghost')),
 (b'Aegislash', ('Steel', 'Ghost')),
 (b'Spritzee', ('Fairy',)),
 (b'Aromatisse', ('Fairy',)),
 (b'Swirlix', ('Fairy',)),
 (b'Slurpuff', ('Fairy',)),
 (b'Inkay', ('Dark', 'Psychic')),
 (b'Malamar', ('Dark', 'Psychic')),
 (b'Binacle', ('Rock', 'Water')),
 (b'Barbaracle', ('Rock', 'Water')),
 (b'Skrelp', ('Poison', 'Water')),
 (b'Dragalge', ('Poison', 'Dragon')),
 (b'Clauncher', ('Water',)),
 (b'Clawitzer', ('Water',)),
 (b'Helioptile', ('Electric', 'Normal')),
 (b'Heliolisk', ('Electric', 'Normal')),
 (b'Tyrunt', ('Rock', 'Dragon')),
 (b'Tyrantrum', ('Rock', 'Dragon')),
 (b'Amaura', ('Rock', 'Ice')),
 (b'Aurorus', ('Rock', 'Ice')),
 (b'Sylveon', ('Fairy',)),
 (b'Hawlucha', ('Fighting', 'Flying')),
 (b'Dedenne', ('Electric', 'Fairy')),
 (b'Carbink', ('Rock', 'Fairy')),
 (b'Goomy', ('Dragon',)),
 (b'Sliggoo', ('Dragon',)),
 (b'Goodra', ('Dragon',)),
 (b'Klefki', ('Steel', 'Fairy')),
 (b'Phantump', ('Ghost', 'Grass')),
 (b'Trevenant', ('Ghost', 'Grass')),
 (b'Pumpkaboo', ('Ghost', 'Grass')),
 (b'Gourgeist', ('Ghost', 'Grass')),
 (b'Bergmite', ('Ice',)),
 (b'Avalugg', ('Ice',)),
 (b'Noibat', ('Flying', 'Dragon')),
 (b'Noivern', ('Flying', 'Dragon')),
 (b'Xerneas', ('Fairy',)),
 (b'Yveltal', ('Dark', 'Flying')),
 (b'Zygarde', ('Dragon', 'Ground'))][int(input())-1]

print(pk[0].decode('utf-8'))
if len(pk[1])==1: print(pk[1][0])
else: print(pk[1][0]+' '+pk[1][1])